import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { Box, Container, Grid, GridItem, Heading } from "@chakra-ui/react";
import TeamCard from "../components/TeamCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Team - MINeD 2024 Hackathon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW={"container.xl"} marginInline="auto">
        <Navbar />
        <Box marginBlock={16}>
          <Heading
            paddingBlock={8}
            textAlign={["center"]}
            textDecoration="underline"
          >
            Meet Our Team
          </Heading>
          <Heading
            size={"lg"}
            color={"blue.400"}
            textAlign={["center"]}
            paddingBlock={4}
          >
            Advisors
          </Heading>
          <Advisor />
          <Heading
            size={"lg"}
            color={"blue.400"}
            textAlign={["center"]}
            paddingBlock={4}
          >
            Coordinators
          </Heading>
          <Coordinators />
          <Heading
            size={"lg"}
            color={"blue.400"}
            textAlign={["center"]}
            paddingBlock={4}
          >
            Team Members
          </Heading>
          <Developers />
        </Box>
        <Footer />
      </Container>
    </>
  );
}

function Coordinators() {
  const coordinators = [
    {
      name: "Dr Sapan H Mankad",
      image: "/sapan_mankad.jpg",
      linkedIn: "https://www.linkedin.com/in/sapan-mankad-4815601a/",
    },
    {
      name: "Dr Vishal Parikh",
      image: "/vishal_parikh.jpg",
      linkedIn: "https://technology.nirmauni.ac.in/author/vishalparikh/",
    },
    {
      name: "Dr Rupal Kapdi",
      image: "/rupal_kapdi.jpeg",
      linkedIn: "https://www.linkedin.com/in/dr-rupal-kapdi-474620256",
    },
  ];
  return (
    <Grid
      h="auto"
      templateRows={{ sm: "repeat(8, 1fr)", md: "repeat(1, 1fr)" }}
      templateColumns={{ sm: "repeat(1, 1fr)", md: "repeat(3, 1fr)" }}
      gap={4}
      marginBottom={8}
    >
      {coordinators.map((ad) => (
        <GridItem>
          <TeamCard
            url={ad.image}
            name={ad.name}
            description={""}
            link={ad.linkedIn}
          />
        </GridItem>
      ))}
    </Grid>
  );
}
function Advisor() {
  const advisors = [
    {
      name: "Dr R N Patel",
      designation: "Director",
      image: "/dr_rn_patel.jpg",
      linkedIn: "https://www.linkedin.com/in/rajesh-patel-b5144256/",
    },
    {
      name: "Dr Madhuri Bhavsar",
      image: "/dr_madhuri_bhavsar.jpg",
      linkedIn: "https://www.linkedin.com/in/dr-madhuri-gujar-bhavsar-3bb61a6/",
    },
    {
      name: "Dr Sangwon Yoon",
      image: "/dr_yoon.jpg",
      linkedIn: "https://www.linkedin.com/in/sang-won-yoon-bb886722/",
    },
    {
      name: "Dr Priyank Thakkar",
      image: "/priyank_thakkar.jpg",
      linkedIn: "https://www.linkedin.com/in/priyank-thakkar-4701689b/",
    },
    {
      name: "Dr Swati Jain",
      image: "/swati_jain.jpg",
      linkedIn: "https://www.linkedin.com/in/swati-jain-54845311/",
    },
  ];
  return (
    <Grid
      h="auto"
      templateRows={{ sm: "repeat(8, 1fr)", md: "repeat(1, 1fr)" }}
      templateColumns={{ sm: "repeat(1, 1fr)", md: "repeat(4, 1fr)" }}
      gap={4}
      marginBottom={8}
    >
      {advisors.map((ad) => (
        <GridItem>
          <TeamCard
            url={ad.image}
            name={ad.name}
            description={ad.designation ?? "Advisor"}
            link={ad.linkedIn}
          />
        </GridItem>
      ))}
    </Grid>
  );
}

function Developers() {
  const developers = [
    {
      name: "Vanshil Vaghasiya",
      image: "/vanshil.jpeg",
      linkedIn: "https://www.linkedin.com/in/vanshilpatel/",
    },
    {
      name: "Naitik Prajapati ",
      image: "/naitik.png",
      linkedIn: "https://www.linkedin.com/in/naitik554/",
    },
    {
      name: "Urvish Patel",
      image: "/urvish.jpeg",
      linkedIn: "https://linkedin.com/in/urvishpatel1609/",
    },
    {
      name: "Parthraj Mori",
      image: "/parthraj.jpeg",
      linkedIn: "https://www.linkedin.com/in/parthrajsinh-mori-2010b0274/",
    },
    {
      name: "Priyang Desai",
      image: "/priyang.jpeg",
      linkedIn: "https://www.linkedin.com/in/priyang-desai1310",
    },
    {
      name: "Jaimin Salvi",
      image: "/jaimin.jpeg",
      linkedIn: "https://www.linkedin.com/in/jaimin-salvi-6786442a6/?trk=contact-info",
    },
    {
      name: "Het Chaudhari",
      image: "/het.jpeg",
      linkedIn: "https://www.linkedin.com/in/het-chaudhari-70288728a/",
    },
  ];
  return (
    <Grid
      h="auto"
      templateRows={{ sm: "repeat(8, 1fr)", md: "repeat(1, 1fr)" }}
      templateColumns={{ sm: "repeat(1, 1fr)", md: "repeat(4, 1fr)" }}
      gap={4}
      marginBottom={8}
    >
      {developers.map((dev) => (
        <GridItem>
          <TeamCard
            url={dev.image}
            name={dev.name}
            description={""}
            link={dev.linkedIn}
          />
        </GridItem>
      ))}
    </Grid>
  );
}
